services:
  postgres:
    build:
      context: .
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD}
      POSTGRES_USER: ${DEFAULT_USERNAME}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:${DEFAULT_DATABASE_PATH}
    restart: always

volumes:
  postgres_data: