services:
  postgres:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DEFAULT_PASSWORD}
      POSTGRES_USER: ${DEFAULT_USERNAME}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      device: ${DEFAULT_DATABASE_PATH}
      o: 'bind'

networks:
  default:
    driver: bridge
